### ISSUE TITLE
第4章 開発課題 課題2 テーブル設計

### ISSUE THREAD

**Issue by tunacats** [tunacats/lamp_practice#10]
■開発条件
　【購入履歴画面】
　- [✔] 現在ログイン中のユーザーの購入履歴を表形式で一覧表示
　- [✔*] 管理者ユーザーについては全ての購入履歴を表形式で一覧表示。
　- [✔] 表示項目は「注文番号」「購入日時」「該当の注文の合計金額」とする。
　- [✔] 注文番号は、購入完了のたびにオートインクリメントで付番されるものとする。
　- [✔] 各行の末尾に「購入明細表示」のボタンを配置する。
　- [✔] ソート順は注文の新着順とする。

　【購入明細画面】
　- [✔] 該当の注文番号の購入明細を表形式で一覧表示する。
　- [✔] 表示項目は「商品名」「購入時の商品価格」 「購入数」「小計」とする。
　- [✔] 画面上部に該当の「注文番号」「購入日時」「合計金額」を表示する。
　- [✔] ログインユーザー以外の注文については、管理者以外は閲覧できないものとする。

■課題2-1 - 追加テーブルの設計
　・購入履歴画面を表示するためにはどのようなテーブルが必要か。
　・購入明細画面を表示するためにはどのようなテーブルが必要か。
　※正規化の観点から適切にテーブルを分割して、不要なカラムは含めないこと。

　- [✔] append_schema.sqlの提出
 
■課題2-2 : 追加テーブルへのデータ保存
　・購入履歴画面、購入明細画面の出力に必要なデータを適切な箇所へ保存
　・購入履歴・購入明細を保存する処理はどのコントローラで行うのが適切か判断する
　※適切にトランザクション処理を利用する

　- [✔] 購入履歴画面の出力に必要なデータをデータベースへ保存する処理の作成
　- [✔] データベースに購入履歴画面の出力に必要なデータが保存されていることを確認
　- [✔] 購入明細画面の出力に必要なデータをデータベースへ保存する処理の作成
　- [✔]  データベースに購入明細画面の出力に必要なデータが保存されていることを確認
　- [✔] トランザクション処理が正常に動作することを確認

■課題2-3: 追加画面の作成
　・課題2-2で保存したレコードを利用して購入履歴/購入明細画面の作成

　【購入履歴画面】
　- [✔] order_history.php (Controller)
　- [✔] order_history_view.php (View)

　【購入明細画面】
　- [✔] order_detail.php (Controller)
　- [✔] order_detail_view.php (View)
　
　【共通】
　- [✔] order_history.php (Model)

**Comment by primestyleus** [comment]
@tunacats 

こちら詳細にありがとうございます！まずは２−１から進めていただければと思います！

まだ先ではありますが、2−3の部分でモデルファイル名が「order_histories.php」と複数形になっているのが多少気になります。既存のコードはMySQL上でのテーブル名は複数形、PHPでのモデル名は単数形で統一されているようです。

**Comment by tunacats** [comment]
valueのところに関しては、課題３で実施いたします。
一旦課題２は終了し、本Issueはクローズします。
