### ISSUE TITLE
課題1 ランキング機能 (難易度：低)

### ISSUE THREAD

**Issue by tunacats** [tunacats/lamp_practice#14]
一旦課題1のランキング機能を作成し、間に合うようであれば並べ替え機能の実装を予定しています。
※前回ご指摘いただいたnumber_formatの件についてもこちら修正を行います。

ページネーションについては、25日以降に予定をいれさせていただきますので、そこで相談させてください。

■要件
　- [ ] 商品一覧ページ下部に「人気ランキング」を表示する
　- [ ] 「人気ランキング」には、購入数の多い順に1位から3位の商品を表示させる
■ヒント
　SUMを利用して商品ごとの全てのユーザーの購入数を求めることができます。
　ORDER BY 句でユーザーの購入数を基準に並べ替えることができます。
　LIMIT 句を利用して利用して上位x件のデータを取得できます。

**Comment by primestyleus** [comment]
@tunacats 
課題の進め方について承知しました。issue は課題ごとにそれぞれ別に作成して進めていただけますでしょうか？

**Comment by tunacats** [comment]
@primestyleus 
承知いたしました。分割するようにいたします

**Comment by tunacats** [comment]
実装完了いたしましたので、本Issueはクローズさせていただきます。
